# **Introduction to Python.**
Topics
- Input, Output
- Loops, If else
- Lists 
- Sets 
- Tuples
- Dictionary
- Numpy 

Cuarted By Abhijit Paul (Core Team Member- MOSS)

## **Input**

We often have a need to interact with users, either to get data or to provide some sort of result. Most programs today use a dialog box as a way of asking the user to provide some type of input. While Python 3 provides us with inbuilt functions to read the input from the keyboard.



###input ('prompt') 
- This function first takes the input from the user and then evaluates the expression, which means Python automatically identifies whether user entered a string or a number or list. If the input provided is not correct then either syntax error or exception is raised by python.


In [ ]:
# Example of input function.

In [ ]:
x = input('Enter the value: ')


###How the input function works in Python :

- When input() function executes program flow will be stopped until the user has given an input.
- The text or message display on the output screen to ask a user to enter input value is optional i.e. the prompt, will be printed on the screen is optional.
- Whatever you enter as input, input function convert it into a string. if you enter an integer value still input() function convert it into a string.

##**Output**

- Python print() function prints the message to the screen or any other standard output device.

**Syntax**


In [ ]:
print(value(s))

# value(s): Any value, and as many as you like. Will be converted to string before printed

**Example**

In [ ]:
# The above input value of x will be printed by print() function.

In [ ]:
print(x)

##**Loops**

Python mainly consists of two type of loops
1. while loop
2. for loop

### 1. While Loop: 
- In python, while loop is used to execute a block of statements repeatedly until a given condition is satisfied. And when the condition becomes false, the line immediately after the loop in the program is executed.

- Syntax :
 





In [ ]:
while expression:
  statement(s)

# code will run till expression is true

- All the statements indented by the same number of character spaces after a while keyword are considered to be part of a single block of code. Python uses indentation as its method of grouping statements. 

**The following code will run till the expression becomes false**



In [ ]:
x = 0 
while x < 3:
  print('Namaste') 

**The above code is an infinite loop i.e it will run forever till your devices runs out of memory or power.**
**So, we need to add a condition.**

In [ ]:
x = 0
while x < 3:
  x = x + 1
  print('Namaste')

**Therefore the above code run till x = 2, after that the expression becomes false and it comes out of the loop. As the value of x increase every time the loop runs.**

###2. For loop

-  For loops are used for sequential traversal. For example: traversing a list or string or array etc

- Syntax:


 


In [ ]:
for iterator_var in sequence:
  statements(s)

- It can be used to iterate over a range and iterators.

**The following code will show the use of for loop till the condition is false**

In [ ]:
n = 4
for i in range(0, 4):
  print(i)

**We can also write the following code without providing the first value as by default it is zero(0)**

In [ ]:
for i in range(4):
  print(i)

##**If else**

1. if statement
2. if-else statement
3. if-elif-else statement



There comes situations in real life when we need to make some decisions and based on these decisions, we decide what should we do next. Similar situations arise in programming also where we need to make some decisions and based on these decisions we will execute the next block of code. Decision-making statements in programming languages decide the direction of the flow of program execution. 

In Python, if else elif statement is used for decision making.

###1. if statement

- if statement is the most simple decision-making statement. It is used to decide whether a certain statement or block of statements will be executed or not i.e if a certain condition is true then a block of statement is executed otherwise not.

**Syntax**: 



In [ ]:
if condition:
   # Statements to execute if condition is true

- Here, the condition after evaluation will be either true or false. if statement accepts boolean values – if the value is true then it will execute the block of statements below it otherwise not.

**As we know, python uses indentation to identify a block. So the block under an if statement will be identified as shown in the below example:**  

In [ ]:
if condition:
   statement1
statement2

# Here if the condition is true, if block will consider only statement1 to be inside its block.

**Example: Python if Statement**

In [ ]:
i = 10

if (i > 15):
	print("10 is less than 15")
print("I am Not in if")


- As the condition present in the if statement is false. So, the block below the if statement is not executed.

###2. if-else statement



- The if statement alone tells us that if a condition is true it will execute a block of statements and if the condition is false it won’t. But what if we want to do something else if the condition is false. Here comes the else statement. We can use the else statement with if statement to execute a block of code when the condition is false. 

**Syntax:**

In [ ]:
if (condition):
    # Executes this block if condition is true
else:
    # Executes this block if condition is false

Example: Python if else statement

In [ ]:
i = 20
if (i < 15):
    print("I is smaller than 15")
    print("I'm in if Block")
else:
    print("I is greater than 15")
    print("I'm in else Block")

The block of code following the else statement is executed as the condition present in the if statement is false

###3. if-elif-else statement

- Here, a user can decide among multiple options. The if statements are executed from the top down. As soon as one of the conditions controlling the if is true, the statement associated with that if is executed, and the rest of the ladder is bypassed. If none of the conditions is true, then the final else statement will be executed.

**Syntax:**

In [ ]:
if (condition):
    statement
elif (condition):
    statement
else:
    statement

**Example: Python if else elif statements**

In [ ]:
i = 20
if (i == 10):
    print("i is 10")
elif (i == 15):
    print("i is 15")
elif (i == 20):
    print("i is 20")
else:
    print("i is not present")

##**Lists**
- Lists are data types, they need not be homogeneous always. A single list may contain DataTypes like Integers, Strings, as well as Objects. Lists are mutable, and hence, they can be altered even after their creation.
- List in Python are ordered and have a definite count. The elements in a list are indexed according to a definite sequence and the indexing of a list is done with 0 being the first index. Each element in the list has its definite place in the list, which allows duplicating of elements in the list, with each element having its own distinct place and credibility.

###Creating a List
- Lists in Python can be created by just placing the sequence inside the square brackets[ ]. 

In [ ]:
# Python program to demonstrate Creation of List
# Creating a List
List = []
print("Blank List: ")
print(List,"\n")

# Creating a List of numbers
List = [10, 20, 14]
print("List of numbers: ")
print(List,"\n")

# Creating a List of strings and accessing
# using index
List = ["Manipal", "Institute", "of","Technology"]
print("List Items: ","\n")
print(List[0])
print(List[1])
print(List[3])

- A list may contain duplicate values with their distinct positions and hence, multiple distinct or duplicate values can be passed as a sequence at the time of list creation.

In [ ]:
# Creating a List with the use of Numbers (Having duplicate values)
List = [1, 2, 4, 4, 3, 3, 3, 6, 5]
print("List with the use of Numbers: ")
print(List,"\n")

# Creating a List with mixed type of values (Having numbers and strings)
List = [1, 2, 'Geeks', 4, 'For', 6, 'Geeks']
print("List with the use of Mixed Values: ")
print(List)


**Knowing the size of List**
- len() is a build-in function which can be used to determine the length of a list.



In [ ]:
List = [10, 20, 14]
print(len(List))

###Adding Elements to a List
1. append() method.
2. insert() method.
3. extend() method.



**1. Using append() method**
-  Elements can be added to the List by using the built-in append() function. Only one element at a time can be added to the list by using the append() method, for the addition of multiple elements with the append() method, loops are used.

In [ ]:
# Python program to demonstrate Addition of elements in a List
# Creating a List
List = []
print("Initial blank List: ")
print(List)
# Addition of Elements in the List
List.append(1)
List.append(2)
List.append(4)
print("List after Addition of Three elements: ")
print(List)
# Adding elements to the List using Iterator
for i in range(1, 4):
	List.append(i)
print("List after Addition of elements from 1-3: ")
print(List)
# Addition of List to a List
List2 = ['Messi', 'Ronaldo']
List.append(List2)
print("List after Addition of a List: ")
print(List)


**2. Using insert() method**
- append() method only works for the addition of elements at the end of the List, for the addition of elements at the desired position, insert() method is used. Unlike append() which takes only one argument, the insert() method requires two arguments(position, value). 

**Syntax:**
- insert(position,value).

In [ ]:
# Python program to demonstrate addition of elements in a List
# Creating a List
List = [1,2,3,4]
print("Initial List: ")
print(List)
# Addition of Element at specific Position (using Insert Method)
List.insert(3, 12)
List.insert(0, 'Python')
print("List after performing Insert Operation: ")
print(List)


**3. Using extend() method**
- Other than append() and insert() methods, there’s one more method for the Addition of elements, extend(), this method is used to add multiple elements at the same time at the end of the list.

- Note:
 - append() and extend() methods can only add elements at the end.
 - insert() can add element at any desired position.

In [ ]:
# Python program to demonstrate addition of elements in a List
# Creating a List
List = [1, 2, 3, 4]
print("Initial List: ")
print(List)
# Addition of multiple elements to the List at the end (using Extend Method)
List.extend([8, 'Abc', 'Def'])
print("List after performing Extend Operation: ")
print(List)


###Accessing elements from the List
- In order to access the list items refer to the index number. Use the index operator [ ] to access an item in a list. The index must be an integer. Nested lists are accessed using nested indexing. 

**Syntax:** for accessing nested or multi-dimension list.
- list[ To access the nested/Multi-Dimensional list] [ To access the element inside the nested/Multi-Dimensional list ]

In [ ]:
# Python program to demonstrate accessing of element from list
# Creating a List with the use of multiple values
List = ["Abc", "Def", "Xyz"]

# Accessing a element from the list using index number
print("Accessing a element from the list")
print(List[0])
print(List[2])

# Creating a Multi-Dimensional List (By Nesting a list inside a List)
list =[[1,2,3],[4,5,6],[7,8,9]]
print("Accessing the first Multi-Dimensional list")
print(list[0]) 
print("Accessing the second Multi-Dimensional list")
print(list[1])
print("Accessing the second element of the third Multi-Dimensional list")
print(list[2][1])



**Negative indexing**
- In Python, negative sequence indexes represent positions from the end of the list. Instead of having to compute the offset as in List[len(List)-3], it is enough to just write List[-3]. Negative indexing means beginning from the end, -1 refers to the last item, -2 refers to the second-last item, etc.

In [ ]:
List = [1, 2, 'Abc', 4, 'Def', 6, 'Xyz']

# Accessing an element using negative indexing
print("Accessing element using negative indexing")

# print the last element of list
print(List[-1])

# print the third last element of list
print(List[-3])


###Removing Elements from the List
1. Using remove() method.
2. Using pop() method.

**1. Using remove() method.**
- Elements can be removed from the List by using the built-in remove() function but an Error arises if the element doesn’t exist in the list. Remove() method only removes one element at a time, to remove a range of elements, the iterator is used. The remove() method removes the specified item.

In [ ]:
# Python program to demonstrate removal of elements in a List
# Creating a List
List = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print("Initial List: ")
print(List)

# Removing elements from List using Remove() method
List.remove(5)
List.remove(6)
print("List after Removal of two elements: ")
print(List)

# Removing elements from List using iterator method
for i in range(1, 5):
	List.remove(i)
print("List after Removing a range of elements: ")
print(List)


**2. Using pop() method**
- Pop() function can also be used to remove and return an element from the list, but by default it removes only the last element of the list, to remove an element from a specific position of the List, the index of the element is passed as an argument to the pop() method.

In [ ]:
List = [1,2,3,4,5]

# Removing element from the list using the pop() method
List.pop()
print("List after popping an element: ")
print(List)

# Removing element at a specific location from the list using the pop() method
List.pop(2) 
print("\nList after popping a specific element: ")
print(List)


###Slicing of a List
- In Python List, there are multiple ways to print the whole List with all the elements, but to print a specific range of elements from the list, we use the Slice operation. Slice operation is performed on Lists with the use of a colon( : ). To print elements from beginning to a range use [ : Index ], to print elements from end-use [ : -Index ], to print elements from specific Index till the end use [ Index: ], to print elements within a range, use [ Start Index : End Index ] and to print the whole List with the use of slicing operation, use [ : ]. Further, to print the whole List in reverse order, use [ : : -1 ].

In [ ]:
# Python program to demonstrate removal of elements in a List
# Creating a List
List = ['A', 'B', 'C', 'D', 'E', 'F','G', 'H', 'I', 'J', 'K', 'L', 'M']
print("Initial List: ")
print(List,"\n")

# Print elements of a range using Slice operation
Sliced_List = List[3:8]
print("Slicing elements in a range 3-8: ")
print(Sliced_List,"\n")

# Print elements from a
# pre-defined point to end
Sliced_List = List[5:]
print("Elements sliced from 5th element till the end: ")
print(Sliced_List,"\n")

# Printing elements from
# beginning till end
Sliced_List = List[:]
print("Printing all elements using slice operation: ")
print(Sliced_List,"\n")


**Negative index List slicing**

In [ ]:
# Creating a List
List = ['A', 'B', 'C', 'D', 'E', 'F',	'G', 'H', 'I', 'J', 'K', 'L', 'M']
print("Initial List: ")
print(List,"\n")

# Print elements from beginning
# to a pre-defined point using Slice
Sliced_List = List[:-6]
print("Elements sliced till 6th element from last: ")
print(Sliced_List,"\n")

# Print elements of a range
# using negative index List slicing
Sliced_List = List[-6:-1]
print("Elements sliced from index -6 to -1")
print(Sliced_List,"\n")

# Printing elements in reverse
# using Slice operation
Sliced_List = List[::-1]
print("Printing List in reverse: ")
print(Sliced_List,"\n")


##**Sets**
- In Python, Set is an unordered collection of data type that is iterable, mutable and has no duplicate elements. The order of elements in a set is undefined though it may consist of various elements. 
- The major advantage of using a set, as opposed to a list, is that it has a highly optimized method for checking whether a specific element is contained in the set.

###Creating a Set
- Sets can be created by using the built-in set( ) function with an iterable object or a sequence by placing the sequence inside curly braces, separated by ‘comma’.

In [ ]:
# Python program to demonstrate creation of Set in Python
# Creating a Set
set1 = set()
print("Initial blank Set: ")
print(set1,"\n")

# Creating a Set with the use of a String
set1 = set("ABCDEFGHIJKLM")
print("Set with the use of String: ")
print(set1,"\n")

# Creating a Set with the use of a List
set1 = set(["Abc", "Def", "Xyz"])
print("Set with the use of List: ")
print(set1)


- A set contains only unique elements but at the time of set creation, multiple duplicate values can also be passed. Order of elements in a set is undefined and is unchangeable. Type of elements in a set need not be the same, various mixed up data type values can also be passed to the set. 

In [ ]:
# Creating a Set with a List of Numbers (Having duplicate values)
set1 = set([1, 2, 4, 4, 3, 3, 3, 6, 5])
print("Set with the use of Numbers: ")
print(set1,"\n")

# Creating a Set with a mixed type of values (Having numbers and strings)
set1 = set([1, 2, 'Abc', 4, 'Def', 6, 'Xyz'])
print("Set with the use of Mixed Values")
print(set1)


###Adding Elements to a Set
1. Using add() method
2. Using update() method

**1. Using add() method**
- Elements can be added to the Set by using built-in add() function. Only one element at a time can be added to the set by using add() method, loops are used to add multiple elements at a time with the use of add() method.

In [ ]:
# Python program to demonstrate addition of elements in a Set
# Creating a Set
set1 = set()
print("Initial blank Set: ")
print(set1,"\n")

# Adding element and tuple to the Set
set1.add(8)
set1.add(9)
print("Set after Addition of Three elements: ")
print(set1,"\n")

# Adding elements to the Set using Iterator
for i in range(1, 6):
	set1.add(i)
print("Set after Addition of elements from 1-5: ")
print(set1)


**2. Using update() method**
- For addition of two or more elements Update() method is used. The update() method accepts lists, strings, tuples as well as other sets as its arguments. In all of these cases, duplicate elements are avoided.

In [ ]:
# Python program to demonstrate addition of elements in a Set

# Addition of elements to the Set using Update function
set1 = set([ 4, 5, (6, 7)])
set1.update([10, 11])
print("Set after Addition of elements using Update: ")
print(set1)


###Accessing a Set
- Set items cannot be accessed by referring to an index, since sets are unordered the items has no index. But you can loop through the set items using a for loop, or ask if a specified value is present in a set, by using the in keyword.

In [ ]:
# Python program to demonstrate accessing of elements in a set
# Creating a set
set1 = set(["Abc", "Def", "Xyz"])
print("Initial set")
print(set1,"\n")

# Accessing element using for loop
print("Elements of set: ")
for i in set1:
	print(i,"\n", end="")

# Checking the element using in keyword
print("\nIs Xyz present in the set: ")
print("Xyz" in set1)


###Removing elements from the Set
1. Using remove() method or discard() method
2. Using pop() method
3. Using clear() method

**1. Using remove() method or discard() method**
- Elements can be removed from the Set by using built-in remove() function but a KeyError arises if element doesn’t exist in the set. To remove elements from a set without KeyError, use discard(), if the element doesn’t exist in the set, it remains unchanged.

In [ ]:
# Python program to demonstrate  deletion of elements in a Set
# Creating a Set
set1 = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Initial Set: ")
print(set1,"\n")
  
# Removing elements from Set using Remove() method
set1.remove(5)
set1.remove(6)
print("Set after Removal of two elements: ")
print(set1,"\n")
  
# Removing elements from Set using Discard() method
set1.discard(8)
set1.discard(9)
print("Set after Discarding two elements: ")
print(set1,"\n")
  
print("Removing elements from Set using iterator method")
for i in range(1, 5):
    set1.remove(i)
print("Set after Removing a range of elements: ")
print(set1)

**2. Using pop() method**
- Pop() function can also be used to remove and return an element from the set, but it removes only the last element of the set. 
- Note – If the set is unordered then there’s no such way to determine which element is popped by using the pop() function. 

In [ ]:
# Python program to demonstrate  deletion of elements in a Set
# Creating a Set
set1 = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Initial Set: ")
print(set1,"\n")
  
# Removing element from the set using the pop() method
set1.pop()
print("Set after popping an element: ")
print(set1)

**3. Using clear() method**
- To remove all the elements from the set, clear() function is used. 

In [ ]:
#Creating a set
set1 = set([1,2,3,4,5])
print("Initial set: ")
print(set1,"\n")
  
# Removing all the elements from set using clear() method
set1.clear()
print("Set after clearing all the elements: ")
print(set1)

Initial set: 
{1, 2, 3, 4, 5} 

Set after clearing all the elements: 
set()


##**Tuples**
- Tuple is a collection of Python objects much like a list. The sequence of values stored in a tuple can be of any type, and they are indexed by integers. 
- The important difference is that tuples are immutable.
- Values of a tuple are syntactically separated by ‘commas’. Although it is not necessary, it is more common to define a tuple by closing the sequence of values in parentheses. This helps in understanding the Python tuples more easily.

###Creating a Tuple
- In Python, tuples are created by placing a sequence of values separated by ‘comma’ with or without the use of parentheses for grouping the data sequence.

- Note: Creation of Python tuple without the use of parentheses is known as Tuple Packing. 

In [ ]:
# Creating an empty Tuple
Tuple1 = ()
print("Initial empty Tuple: ")
print(Tuple1,"\n")

# Creating a Tuple with the use of string
Tuple1 = ('Abc', 'Xyz')
print("Tuple with the use of String: ")
print(Tuple1,"\n")

# Creating a Tuple with the use of list
list1 = [1, 2, 4, 5, 6]
print("Tuple using List: ")
print(tuple(list1),"\n")

# Creating a Tuple with the use of built-in function
Tuple1 = tuple('ABCDE')
print("\nTuple with the use of function: ")
print(Tuple1)


**Creating a Tuple with Mixed Datatypes.**
- Tuples can contain any number of elements and of any datatype (like strings, integers, list, etc.). Tuples can also be created with a single element, but it is a bit tricky. Having one element in the parentheses is not sufficient, there must be a trailing ‘comma’ to make it a tuple. 

In [ ]:
# Creating a Tuple with Mixed Datatype
Tuple1 = (5, 'Welcome', 7, 'Peeps')
print("Tuple with Mixed Datatypes: ")
print(Tuple1,"\n")

# Creating a Tuple with nested tuples
Tuple1 = (0, 1, 2, 3)
Tuple2 = ('python', 'code')
Tuple3 = (Tuple1, Tuple2)
print("Tuple with nested tuples: ")
print(Tuple3,"\n")

# Creating a Tuple with repetition
Tuple1 = ('Abcd',) * 3
print("Tuple with repetition: ")
print(Tuple1)


###Accessing of Tuples
- Tuples are immutable, and usually, they contain a sequence of heterogeneous elements that are accessed via unpacking or indexing (or even by attribute in the case of named tuples).
- Note: In unpacking of tuple number of variables on the left-hand side should be equal to a number of values in given tuple a. 

In [ ]:
# Accessing Tuple with Indexing
Tuple1 = tuple("ABCD")
print("First element of Tuple: ")
print(Tuple1[0])

# Tuple unpacking
Tuple1 = ("Abc", "Def", "Xyz")

# This line unpack values of Tuple1
a, b, c = Tuple1
print("Values after unpacking: ")
print(a)
print(b)
print(c)


###Concatenation of Tuples
- Concatenation of tuple is the process of joining two or more Tuples. Concatenation is done by the use of ‘+’ operator.

In [ ]:
# Concatenation of tuples
Tuple1 = (0, 1, 2, 3)
Tuple2 = ('Abc', 'Def', 'Xyz')

Tuple3 = Tuple1 + Tuple2

# Printing first Tuple
print("Tuple 1: ")
print(Tuple1,"\n")

# Printing Second Tuple
print("Tuple2: ")
print(Tuple2)

# Printing Final Tuple
print("\nTuples after Concatenation: ")
print(Tuple3)


###Slicing of Tuple
- Slicing of a Tuple is done to fetch a specific range or slice of sub-elements from a Tuple. 

In [ ]:
# Slicing of a Tuple with Numbers
Tuple1 = tuple('ABCDEFGHI')

# Removing First element
print("Removal of First Element: ")
print(Tuple1[1:],"\n")

# Reversing the Tuple
print("Tuple after sequence of Element is reversed: ")
print(Tuple1[::-1],"\n")

# Printing elements of a Range
print("Printing elements between Range 4-9: ")
print(Tuple1[4:9])


###Deleting a Tuple
- Tuples are immutable and hence they do not allow deletion of a part of it. The entire tuple gets deleted by the use of del( ) method. 
- Note- Printing of Tuple after deletion results in an Error. 

In [ ]:
# Deleting a Tuple

Tuple1 = (0, 1, 2, 3, 4)
del Tuple1

print(Tuple1)


##**Dictionary**
- Dictionary in Python is an unordered collection of data values, used to store data values like a map, which, unlike other Data Types that hold only a single value as an element, Dictionary holds key:value pair. Key-value is provided in the dictionary to make it more optimized. 
 

###Creating a Dictionary
- In Python, a Dictionary can be created by placing a sequence of elements within curly {} braces, separated by ‘comma’. Dictionary holds pairs of values, one being the Key and the other corresponding pair element being its Key:value. Values in a dictionary can be of any data type and can be duplicated, whereas keys can’t be repeated and must be immutable. 
- Note – Dictionary keys are case sensitive, the same name but different cases of Key will be treated distinctly. 

In [ ]:
# Creating a Dictionary with Integer Keys
Dict = {1: 'Abc', 2: 'Def', 3: 'Xyz'}
print("Dictionary with the use of Integer Keys: ")
print(Dict,"\n")

# Creating a Dictionary with Mixed keys
Dict = {'Name': 'Messi', 1: [1, 2, 3, 4]}
print("Dictionary with the use of Mixed Keys: ")
print(Dict)


- Dictionary can also be created by the built-in function dict(). An empty dictionary can be created by just placing to curly braces{ }. 

In [ ]:
# Creating an empty Dictionary
Dict = {}
print("Empty Dictionary: ")
print(Dict,"\n")

# Creating a Dictionary with dict() method
Dict = dict({1: 'Abc', 2: 'Def', 3:'Xyz'})
print("Dictionary with the use of dict(): ")
print(Dict,"\n")

# Creating a Dictionary with each item as a Pair
Dict = dict([(1, 'Abc'), (2, 'Def')])
print("Dictionary with each item as a pair: ")
print(Dict)


###Adding elements to a Dictionary
- In Python Dictionary, the Addition of elements can be done in multiple ways. One value at a time can be added to a Dictionary by defining value along with the key e.g. Dict[Key] = ‘Value’. Updating an existing value in a Dictionary can be done by using the built-in update( ) method.
- Note- While adding a value, if the key-value already exists, the value gets updated otherwise a new Key with the value is added to the Dictionary.

In [ ]:
# Creating an empty Dictionary
Dict = {}
print("Empty Dictionary: ")
print(Dict,"\n")

# Adding elements one at a time
Dict[0] = 'Abc'
Dict[2] = 'Xyz'
Dict[3] = 1
print("Dictionary after adding 3 elements: ")
print(Dict,"\n")

# Adding set of values to a single Key
Dict['Value_set'] = 2, 3, 4
print("Dictionary after adding 3 elements: ")
print(Dict,"\n")

# Updating existing Key's Value
Dict[2] = 'Welcome'
print("Updated key value: ")
print(Dict)


###Accessing elements from a Dictionary
- In order to access the items of a dictionary refer to its key name. Key can be used inside square brackets. 

In [ ]:
# Python program to demonstrate accessing a element from a Dictionary
# Creating a Dictionary
Dict = {1: 'Abc', 'name': 'Def', 3: 'Xyz'}

# accessing a element using key
print("Accessing a element using key:")
print(Dict['name'],"\n")

# accessing a element using key
print("Accessing a element using key:")
print(Dict[1])


- There is also a method called get( ) that will also help in accessing the element from a dictionary.

In [ ]:
# Creating a Dictionary
Dict = {1: 'Abc', 'name': 'Def', 3: 'Xyz'}

# accessing a element using get() method
print("Accessing a element using get:")
print(Dict.get(3))


###Removing Elements from Dictionary

1. Using del keyword
2. Using pop() method
3. Using popitem() method
4. Using clear() method


**1. Using del keyword**
- In Python Dictionary, deletion of keys can be done by using the del keyword. Using the del keyword, specific values from a dictionary as well as the whole dictionary can be deleted.
- Note: The del Dict will delete the entire dictionary and hence printing it after deletion will raise an Error.

In [ ]:
# Initial Dictionary
Dict = { 5 : 'Abc', 6 : 'Def', 7 : 'Xyz'}
print("Initial Dictionary: ")
print(Dict,"\n")

# Deleting a Key value
del Dict[6]
print("Deleting a specific key: ")
print(Dict)


**2. Using pop() method**
- Pop() method is used to return and delete the value of the key specified.

In [ ]:
# Creating a Dictionary
Dict = {1: 'Abc', 'name': 'Def', 3: 'Xyz'}
print("Dictionary before using pop: ", Dict )

# Deleting a key using pop() method
pop_ele = Dict.pop(1)
print('Dictionary after deletion: ' + str(Dict))
print('Value associated to poped key is: ' + str(pop_ele))


**3. Using popitem() method**
- The popitem() returns and removes an arbitrary element (key, value) pair from the dictionary.

In [ ]:
# Creating Dictionary
Dict = {1: 'Abc', 'name': 'Def', 3: 'Xyz'}

# Deleting an arbitrary key using popitem() function
pop_ele = Dict.popitem()
print("Dictionary after deletion: " + str(Dict))
print("The arbitrary pair returned is: " + str(pop_ele))


**4. Using clear() method**
- All the items from a dictionary can be deleted at once by using clear() method.

In [ ]:
# Creating a Dictionary
Dict = {1: 'Abc', 'name': 'Def', 3: 'Xyz'}


# Deleting entire Dictionary
Dict.clear()
print("Deleting Entire Dictionary: ")
print(Dict)


## **NumPy**

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

### Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

### Using NumPy

- Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

## **Numpy Arrays**

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays

**From a Python List**

- We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

- There are lots of built-in ways to generate Arrays

**Arange**

- Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros and ones**

- Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

**linspace**
- Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [ ]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

### eye

- Creates an identity matrix

In [ ]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Random 

Numpy also has lots of ways to create random number arrays:

**rand**
- Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [ ]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

**randn**

- Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [ ]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

**randint**
- Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

44

In [ ]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

### Array Attributes and Methods

- Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

### Reshape
- Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max,min,argmax,argmin**

- These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

5

### Shape

- Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

**dtype**

- You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

## **NumPy Indexing and Selection**

- In this lecture we will discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr = np.arange(0,11)

In [ ]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection
- The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting

- Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)

- The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

**Fancy Indexing**

- Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

### More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

### Selection

- Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## **NumPy Operations**

### Arithmetic

- You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
import numpy as np
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array Functions

- Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

## **NumPy Exercises** 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

**Import NumPy as np**

**Create an array of 10 zeros** 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**Create an array of 10 ones**

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Create an array of 10 fives**

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

**Create an array of the integers from 10 to 50**

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all the even integers from 10 to 50**

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8**

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

 **Create a 3x3 identity matrix**

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

 **Use NumPy to generate a random number between 0 and 1**

array([ 0.42829726])

**Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution**

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

**Create the following matrix:**

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

**Create an array of 20 linearly spaced points between 0 and 1:**

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

### Numpy Indexing and Selection

- Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Now do the following**

**Get the sum of all the values in mat**

325

**Get the standard deviation of the values in mat**

7.2111025509279782

**Get the sum of all the columns in mat**

array([55, 60, 65, 70, 75])

## **NumPy Exercises - Solutions**




Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

**Import NumPy as np**

In [ ]:
import numpy as np

**Create an array of 10 zeros** 

In [ ]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**Create an array of 10 ones**

In [ ]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Create an array of 10 fives**

In [ ]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

**Create an array of the integers from 10 to 50**

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all the even integers from 10 to 50**

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Create a 3x3 identity matrix**

In [ ]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

**Use NumPy to generate a random number between 0 and 1**

In [ ]:
np.random.rand(1)

array([ 0.42829726])

**Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution**

In [ ]:
np.random.randn(25)

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

**Create the following matrix:**

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

**Create an array of 20 linearly spaced points between 0 and 1:**

In [ ]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

### Numpy Indexing and Selection

- Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Now do the following**

**Get the sum of all the values in mat**

In [ ]:
mat.sum()

325

**Get the standard deviation of the values in mat**

In [ ]:
mat.std()

7.2111025509279782

**Get the sum of all the columns in mat**

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])